---
abstract: 'the cpanm wrapper'
author:
  - KPEE.
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-cpanmw
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  App::cpanmw:
    file: lib/App/cpanmw.pm
    version: '0.03'
requires:
  App::cpanminus: '0'
  File::Which: '0'
  FindBin: '0'
  IO::Callback: '0'
  Term::ANSIColor: '0'
  perl: '5.008001'
  version: '0'
version: '0.03'
x_authority: cpan:KPEE
x_contributors:
  - 'KPEE <kpee.cpan@gmail.com>'
